# See https://pre-commit.com for more information
repos:
  - repo: local
    hooks:
      - id: codespell
        name: codespell
        language: system
        entry: codespell

      - id: mypy
        name: mypy
        language: system
        entry: mypy --pretty --follow-imports=silent
        files: \.py[i]?$

  - repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.5
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format